server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    instance-id: ${SPRING_APPLICATION_INSTANCE_ID:${random.uuid}}
    name: ping-service

ping:
  pong-service:
    url: ${PONG_SERVICE_URL:http://localhost:8080}

    
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:ping-producer-group}
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 0
    compress-message-body-threshold: 4096
    max-message-size: 4194304