server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    instance-id: ${SPRING_APPLICATION_INSTANCE_ID:${random.uuid}}
    name: ping-service

ping:
  pong-service:
    url: ${PONG_SERVICE_URL:http://localhost:8081}