services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pong
      POSTGRES_USER: pong
      POSTGRES_PASSWORD: pong@password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pong"]
      interval: 10s
      timeout: 5s
      retries: 5

  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - namesrv_data:/home/rocketmq/namesrv/store
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    command: sh mqbroker  -n namesrv:9876  -c ../conf/broker.conf
    environment:
      JAVA_OPT_EXT: "-Xms1024m -Xmx1024m -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m"
      NAMESRV_ADDR: "namesrv:9876"
      BROKER_CONFIG: |
        brokerClusterName = DefaultCluster
        brokerName = broker-a
        brokerId = 0
        autoCreateTopicEnable = true
        autoCreateSubscriptionGroup = true
        defaultTopicQueueNums = 4
        brokerIP1 = 127.0.0.1

    depends_on:
      - namesrv

  pong-service:
    build: 
      context: .
      dockerfile: Dockerfile.pong
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pong
      SPRING_DATASOURCE_USERNAME: pong
      SPRING_DATASOURCE_PASSWORD: pong@password
      ROCKETMQ_NAME_SERVER: namesrv:9876
      SPRING_APPLICATION_NAME: pong-service
      SPRING_APPLICATION_INSTANCE_ID: pong-1
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      broker:
        condition: service_started

  ping-services:
    build:
      context: .
      dockerfile: Dockerfile.ping
    environment:
      PONG_SERVICE_URL: http://pong-service:8080
      JAVA_OPTS: "-Xmx256m"
      ROCKETMQ_NAME_SERVER: namesrv:9876
      ROCKETMQ_PRODUCER_GROUP: ping-producer-group
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - pong-service

volumes:
  postgres_data:
  namesrv_data:
  broker_data:
  broker_store:

networks:
  default:
    driver: bridge 