version: '3.8'

services:
  pingpong:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pingpong-services
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./logs:/app/logs

networks:
  default:
    driver: bridge 