apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: pingpong
data:
  POSTGRES_DB: pong
  POSTGRES_USER: pong
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pingpong
type: Opaque
data:
  POSTGRES_PASSWORD: cG9uZ0BwYXNzd29yZA== # pong@password base64编码
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: pingpong
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "pong"]
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pingpong
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432 
    nodePort: 30432
