apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
    spec:
      containers:
      - name: namesrv
        image: apache/rocketmq:5.1.4
        command: ["sh", "mqnamesrv"]
        ports:
        - containerPort: 9876
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: pingpong
spec:
  selector:
    app: rocketmq-namesrv
  ports:
  - port: 9876
    targetPort: 9876
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker
  template:
    metadata:
      labels:
        app: rocketmq-broker
    spec:
      containers:
      - name: broker
        image: apache/rocketmq:5.1.4
        command: ["sh", "mqbroker", "-n", "rocketmq-namesrv:9876"]
        ports:
        - containerPort: 10909
        - containerPort: 10911
        - containerPort: 10912
        env:
        - name: JAVA_OPT_EXT
          value: "-Xms512m -Xmx512m -Xmn256m"
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
  namespace: pingpong
spec:
  selector:
    app: rocketmq-broker
  ports:
  - name: port10909
    port: 10909
    targetPort: 10909
  - name: port10911
    port: 10911
    targetPort: 10911
  - name: port10912
    port: 10912
    targetPort: 10912 